# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V0cdDBFv1AgfthZ1ZC2gInmVAcBJM9rZ
"""

import streamlit as st
import openai
import base64
from io import BytesIO

st.set_page_config(page_title="VoiceBot — Your Personal Voicebot", layout="centered", page_icon="🎤")

# ------------------------------
# 1. OWNER PERSONA (YOUR EXACT WORDS — UNCHANGED)
# ------------------------------
persona_prompt = """
I am a very hardworking person. I do not easily give up when the situations are worse.
I achieve my goals, complete my works and duties even how hard it takes to reach up anywhere.
So to sum up, I can say I am not a quitter. But an evolving person who tries to learn from my situations and duties.

Focused learning. I am a person who can get my complete focus when I trying to learn something or do my work.

I am a person who always develops myself in leadership skills, memory and multitasking skills.
I always write down what I should do at that particular time. In order to develop my leadership skills
I was the part of the bost NCC and it helped me to gain a confidence, independence.
Even I was the part of a social service wing the NSS.

A common misconception my classmate have against me is that things comes easier to me or it goes smoothly to me
without any obstacles. But the reality is different. I do face obstacles and every day is a challenge.

In order to push my boundaries and limits, I keep a track of what all things should be done and act.
I break my big tasks and organize them according so that I wont have a large burden at last.
In order to upcoming changes or anything, I prepare myself by getting my ready according to the situation.
I try to keep things organized, so I can have an idea of what I should do next
"""

# ------------------------------
# 2. Streamlit UI
# ------------------------------
st.title("🎤 VoiceBot — Interview-Style Voice Assistant")
st.write("Click **Record**, ask your question, and the bot will answer in your voice/personality.")

# Input method toggle
mode = st.radio("Choose input method:", ["🎤 Voice Input", "⌨️ Text Input"])

audio_bytes = None
user_text = None

# ------------------------------
# 3. Voice Input (via st.audio_input)
# ------------------------------
if mode == "🎤 Voice Input":
    st.write("Press **Record** to speak:")
    audio_bytes = st.audio_input("")

# ------------------------------
# 4. Text Input
# ------------------------------
else:
    user_text = st.text_input("Type your question here:")

# ------------------------------
# 5. Process User Input
# ------------------------------
def transcribe_audio(audio_bytes):
    audio_file = BytesIO(audio_bytes)
    audio_file.name = "audio.wav"

    transcript = openai.audio.transcriptions.create(
        model="gpt-4o-transcribe",
        file=audio_file
    )
    return transcript.text

def ask_openai(question):
    response = openai.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": f"You must speak in the user's personality: {persona_prompt}"},
            {"role": "user", "content": question}
        ]
    )
    return response.choices[0].message["content"]

# ------------------------------
# 6. Handle Submission
# ------------------------------
if st.button("Submit"):
    final_question = None

    if audio_bytes:
        with st.spinner("Transcribing your voice..."):
            final_question = transcribe_audio(audio_bytes)
            st.write("**Transcript:**", final_question)

    elif user_text and user_text.strip():
        final_question = user_text

    if final_question:
        with st.spinner("Generating answer..."):
            answer = ask_openai(final_question)
            st.success("**VoiceBot Response:**")
            st.write(answer)

    else:
        st.warning("Please record audio or enter text.")

# ------------------------------
# 7. Footer
# ------------------------------
st.markdown("---")
st.caption("Built for your assessment. Works on Streamlit Cloud. No API key entry needed for users.")

